default:
  TOKEN: fill
  LOGS_LOCATION: fill
  DB_LOCATION: fill
  COMMAND_PREFIX: '?'
  JOKE_SOURCE:
    ru_RU:
      name: "nekdo.ru"
      url: "https://nekdo.ru/random/"
    en_US:
      name: "official-joke-api"
      url: "https://official-joke-api.appspot.com/random_joke"
  LIMITATIONS:
    drinks_per_server: 1024
    drink_name_length: 255
    portions_per_day: 10000
    portion_max_size: 10000
    serve_timeout: 600
  INTERNATIONAL:
    greetings_ending: "Choose my language by {0}lang command."
    lang_list: "Below is the list of available languages.
          \nIf you want to add a new language, check our GitHub: https://github.com/6rayWa1cher/bar-counter-discordbot, section \"Localization\".
          \nTo select language, type {0}lang <LANG_CODE>."
    incorrect_language: "There's an incorrect language code."
    missing_permissions: "You haven't the \"Manage Guild\" permission to issue this command."
  LANG:
    ru_RU:
      name: Russian
      greetings: "Ð’ÑÐµÐ¼ Ð¿Ñ€Ð¸Ð²ÐµÑ‚! Ð¯ Ð±Ð¾Ñ‚ {0}, Ð½Ð°Ð»Ð¸Ð²Ð°ÑŽ Ð²Ð°Ð¼ Ð½Ð°Ð¿Ð¸Ñ‚ÐºÐ¸ :D\nÐ¡Ð¿Ñ€Ð°Ð²ÐºÐ° Ð¶Ð¸Ð²ÐµÑ‚ Ð½Ð° {1}help. {2}"
      on_error: "ÐŸÑ€Ð¾Ð¸Ð·Ð¾ÑˆÐ»Ð° Ð½ÐµÐ¿Ñ€ÐµÐ´Ð²Ð¸Ð´ÐµÐ½Ð½Ð°Ñ Ð¾ÑˆÐ¸Ð±ÐºÐ° :("
      lang_selected: "Ð’Ñ‹Ð±Ñ€Ð°Ð½ \"ru_RU\" ÑÐ·Ñ‹Ðº!"
      missing_permissions:
        serve: "Ð£ Ð¼ÐµÐ½Ñ Ð½ÐµÐ´Ð¾ÑÑ‚Ð°Ñ‚Ð¾Ñ‡Ð½Ð¾ Ð¿Ñ€Ð°Ð² Ð´Ð»Ñ ÑÑ‚Ð¾Ð¹ ÐºÐ¾Ð¼Ð°Ð½Ð´Ñ‹. Ð£Ð±ÐµÐ´Ð¸ÑÑŒ, Ñ‡Ñ‚Ð¾ Ñƒ Ð¼ÐµÐ½Ñ ÐµÑÑ‚ÑŒ Ð¿Ñ€Ð°Ð²Ð°
        \"ÐŸÐµÑ€ÐµÐ¼ÐµÑ‰Ð°Ñ‚ÑŒ ÑƒÑ‡Ð°ÑÑ‚Ð½Ð¸ÐºÐ¾Ð²\" Ð¸ \"Ð”Ð¾Ð±Ð°Ð²Ð»ÑÑ‚ÑŒ Ñ€ÐµÐ°ÐºÑ†Ð¸Ð¸\""
      missing_role: "Ð¢Ñ‹ Ð½Ðµ Ð±Ð°Ñ€Ð¼ÐµÐ½, ÑÐ»ÐµÐ´Ð¾Ð²Ð°Ñ‚ÐµÐ»ÑŒÐ½Ð¾, Ñ Ð½Ðµ ÑÐ»ÑƒÑˆÐ°ÑŽÑÑŒ >:D"
      wrong_intoxication: "ÐŸÐ°Ñ€Ð°Ð¼ÐµÑ‚Ñ€ intoxication Ð½Ðµ Ð² Ð³Ñ€Ð°Ð½Ð¸Ñ†Ð°Ñ… Ð¾Ñ‚ 0 Ð´Ð¾ 100."
      wrong_portion_size: "ÐŸÐ°Ñ€Ð°Ð¼ÐµÑ‚Ñ€ portion_size Ð½Ðµ Ð¿Ð¾Ð»Ð¾Ð¶Ð¸Ñ‚ÐµÐ»ÐµÐ½"
      wrong_portions_per_day: "ÐŸÐ°Ñ€Ð°Ð¼ÐµÑ‚Ñ€ portions_per_day Ð½Ðµ Ð¿Ð¾Ð»Ð¾Ð¶Ð¸Ñ‚ÐµÐ»ÐµÐ½"
      wrong_drink_name: "ÐŸÐ°Ñ€Ð°Ð¼ÐµÑ‚Ñ€ drink_name Ð¿ÑƒÑÑ‚ Ð¸Ð»Ð¸ ÐµÐ³Ð¾ Ð´Ð»Ð¸Ð½Ð° Ð¿Ñ€ÐµÐ²Ñ‹ÑˆÐ°ÐµÑ‚ {0} ÑÐ¸Ð¼Ð²Ð¾Ð»Ð¾Ð²"
      drink_not_found: "ÐÐ°Ð¿Ð¸Ñ‚Ð¾Ðº \"{0}\" Ð½Ðµ Ð½Ð°Ð¹Ð´ÐµÐ½"
      drink_deleted: "ÐÐ°Ð¿Ð¸Ñ‚Ð¾Ðº \"{0}\" ÑƒÐ´Ð°Ð»ÐµÐ½"
      drink_added: "Ð”Ð¾Ð±Ð°Ð²Ð¸Ð» \"{0}\" Ð² Ð±Ð°Ñ€"
      duplicate_drink: "Ð¢Ð°ÐºÐ¾Ð¹ Ð½Ð°Ð¿Ð¸Ñ‚Ð¾Ðº ÑƒÐ¶Ðµ ÑÑƒÑ‰ÐµÑÑ‚Ð²ÑƒÐµÑ‚ Ð½Ð° ÑÑ‚Ð¾Ð¼ ÑÐµÑ€Ð²ÐµÑ€Ðµ!"
      ok-emoji: "ðŸ‘"
      no-emoji: "ðŸ‘Ž"
      reset_complete: "Ð¡Ð±Ñ€Ð¾Ñ ÑƒÑÐ¿ÐµÑˆÐ½Ð¾ Ð·Ð°Ð²ÐµÑ€ÑˆÐµÐ½."
      reset_to_defaults_complete: "Ð’Ð¾ÑÑÑ‚Ð°Ð½Ð¾Ð²Ð»ÐµÐ½Ð½Ñ‹ ÑÑ‚Ð°Ð½Ð´Ð°Ñ€Ñ‚Ð½Ñ‹Ðµ Ð½Ð°Ð¿Ð¸Ñ‚ÐºÐ¸"
      restocked_all: "Ð’ÑÐµ Ð·Ð°Ð¿Ð°ÑÑ‹ Ð²Ð¾ÑÐ¿Ð¾Ð»Ð½ÐµÐ½Ñ‹! Ð˜ ÑÐ½Ð¾Ð²Ð° Ð¿Ð¸Ñ‚ÑŒ :D"
      serve_message:
        - "{author} Ð¿Ñ€ÐµÐ´Ð»Ð¾Ð¶Ð¸Ð» Ð²Ð°Ð¼ Ð²Ñ‹Ð¿Ð¸Ñ‚ÑŒ {drink}, {portion_size}Ð¼Ð». Ð¥Ð¾Ñ‚Ð¸Ñ‚Ðµ Ð²Ñ‹Ð¿Ð¸Ñ‚ÑŒ?"
      drink_info: "{0}, Ð¾Ð´Ð½Ð° Ð¿Ð¾Ñ€Ñ†Ð¸Ñ Ñ€Ð°Ð²Ð½Ð° {1}Ð¼Ð», {2}/{3}"
      no_drinks: "ÐÐµÑ‚ Ð½Ð°Ð¿Ð¸Ñ‚ÐºÐ¾Ð²!"
      joke_not_loaded: "Ð¨ÑƒÑ‚ÐµÐµÑ‡ÐºÐ° Ð½Ðµ Ð¿Ð¾Ð´ÑŠÐµÑ…Ð°Ð»Ð° :("
      too_many_drinks: "ÐÐµ Ð¼Ð¾Ð³Ñƒ Ð´Ð¾Ð±Ð°Ð²Ð¸Ñ‚ÑŒ Ð½Ð¾Ð²Ñ‹Ð¹ Ð½Ð°Ð¿Ð¸Ñ‚Ð¾Ðº: Ð¿Ñ€ÐµÐ²Ñ‹ÑˆÐµÐ½ Ð»Ð¸Ð¼Ð¸Ñ‚ Ð² {0} Ð¿Ð¾Ð·Ð¸Ñ†Ð¸Ð¹"
      pre_overdrink:
        - "Ð£ {0} Ð¿Ð¾Ð´ÐµÑ€Ð³Ð¸Ð²Ð°ÑŽÑ‚ÑÑ Ð³Ð»Ð°Ð·Ð°..."
        - "{0} Ð¿Ð¾Ñ‡Ñ‚Ð¸ Ð²ÑÑ‘! Ð‘Ð°Ñ€Ð¼ÐµÐ½, Ð´Ð¾Ð±Ð¸Ð²Ð°Ð¹! >:D"
        - "{0} Ñ‡ÑƒÐ²ÑÑ‚Ð²ÑƒÐµÑ‚ Ð¿Ð¾Ð¼ÑƒÑ‚Ð½ÐµÐ½Ð¸Ðµ Ñ€Ð°ÑÑÑƒÐ´ÐºÐ°"
      overdrink_kick_message:
        - "{0} Ð²Ñ‹Ð¿Ð¸Ð» ÑÐ»Ð¸ÑˆÐºÐ¾Ð¼ Ð¼Ð½Ð¾Ð³Ð¾, ÐµÐ³Ð¾ Ð¾Ñ‚Ð¿Ñ€Ð°Ð²Ð¸Ð»Ð¸ Ð´Ð¾Ð¼Ð¾Ð¹, Ð¿Ð¾ÐºÐ° Ð¾Ð½ Ñ‡ÐµÐ³Ð¾-Ñ‚Ð¾ Ð¸Ð»Ð¸ ÐºÐ¾Ð³Ð¾-Ñ‚Ð¾ Ð½Ðµ ÑÐ»Ð¾Ð¼Ð°Ð»"
        - "{0} ÑƒÐ¿Ð°Ð» Ð½Ð° Ð¿Ð¾Ð». ÐÐµÑ‚, Ð½Ðµ ÐºÐ¾Ñ€Ð¾Ð½Ð°Ð²Ð¸Ñ€ÑƒÑ, Ð½Ð¾ ÐµÐ¼Ñƒ ÑÐ²Ð½Ð¾ Ð¿Ð¾Ñ€Ð° Ð¿Ð¾ÑÐ¿Ð°Ñ‚ÑŒ Ð¸ Ð¿Ñ€Ð¸Ð´Ñ‚Ð¸ Ð² ÑÐµÐ±Ñ..."
        - "Ð“ÐµÑ€Ð¾Ð¸Ñ‡ÐµÑÐºÐ¸ Ð´Ð¾Ð¿Ð¸Ð² ÑÐ²Ð¾Ð¹ Ð½Ð°Ð¿Ð¸Ñ‚Ð¾Ðº, {0} Ñ Ñ€Ð°Ð·Ð¼Ð°Ñ…Ñƒ Ð²ÑÑ‚Ð°Ð», Ð¿Ñ€Ð¾ÑˆÐµÐ» Ð¿Ð°Ñ€Ñƒ Ð¼ÐµÑ‚Ñ€Ð¾Ð² Ð¸ Ð²Ð»ÐµÑ‚ÐµÐ» Ð² ÐºÐ¾Ð»Ð¾Ð½Ð½Ñƒ. Ð•Ð³Ð¾ Ð²Ñ‹Ð»ÐµÑ‡Ð°Ñ‚, Ð½Ðµ Ð²Ð¾Ð»Ð½ÑƒÐ¹Ñ‚ÐµÑÑŒ."
        - "{0} ÑƒÐ±ÐµÐ¶Ð°Ð» Ð² Ñ‚ÑƒÐ°Ð»ÐµÑ‚, ÑÐºÐ¾Ñ€Ð¾ Ð±ÑƒÐ´ÐµÑ‚! (Ð½Ð°Ð²ÐµÑ€Ð½Ð¾Ðµ)"
      overdrink_no_kick_message:
        - "{0} Ð²Ñ‹Ð¿Ð¸Ð» ÑÐ»Ð¸ÑˆÐºÐ¾Ð¼ Ð¼Ð½Ð¾Ð³Ð¾, Ð½Ð¾ Ð±Ð°Ñ€Ð¼ÐµÐ½ Ð¼Ð³Ð½Ð¾Ð²ÐµÐ½Ð½Ð¾ Ð¾Ñ‚Ñ€ÐµÐ·Ð²Ð¸Ð» ÐµÐ³Ð¾ Ñ Ð¿Ð¾Ð¼Ð¾Ñ‰ÑŒÑŽ ÐºÐ°ÐºÐ¾Ð¹-Ñ‚Ð¾ Ð¼Ð°Ð³Ð¸Ð¸"
        - "{0} ÑƒÐ¶Ðµ Ð¿Ð¾ÐºÑ€Ð°ÑÐ½ÐµÐ», Ð½Ð¾ ÐÐºÐ²Ð° ÐµÐ¼Ñƒ Ð¿Ð¾Ð¼Ð¾Ð³Ð»Ð°... ÐžÐ½ ÑÐ½Ð¾Ð²Ð° Ð² ÑÑ‚Ñ€Ð¾ÑŽ ^_^"
      no_portions_left:
        - "{0} Ð·Ð°ÐºÐ¾Ð½Ñ‡Ð¸Ð»Ð¾ÑÑŒ ÑÐ»Ð¸ÑˆÐºÐ¾Ð¼ Ð±Ñ‹ÑÑ‚Ñ€Ð¾..."
        - "{0} Ð·Ð°ÐºÐ¾Ð½Ñ‡Ð¸Ð»Ð¾ÑÑŒ. ÐœÐ¾Ð¶ÐµÑ‚ Ñ‡ÐµÐ³Ð¾-Ñ‚Ð¾ Ð´Ñ€ÑƒÐ³Ð¾Ð³Ð¾, Ð´Ñ€ÑƒÐ³?"
        - "Ðž Ð½ÐµÑ‚! Ð¢Ð¾Ð»ÑŒÐºÐ¾ Ð½Ðµ ÑÑ‚Ð¾!\nÐ•Ð³Ð¾ Ð’ÐµÐ»Ð¸Ñ‡ÐµÑÑ‚Ð²Ð¾, \"{0}\", Ð·Ð°ÐºÐ¾Ð½Ñ‡Ð¸Ð»Ð¾ÑÑŒ :'("
      last_portion:
        - "Ð­Ñ‚Ð¾ Ð±Ñ‹Ð»Ð° Ð¿Ð¾ÑÐ»ÐµÐ´Ð½ÑÑ ÐºÐ°Ð¿Ð»Ñ Ð¿Ñ€ÐµÐºÑ€Ð°ÑÐ½Ð¾Ð³Ð¾ \"{0}\""
        - "ÐŸÐ¾ÑÐ»ÐµÐ´Ð½ÑÑ Ð¿Ð¾Ñ€Ñ†Ð¸Ñ \"{0}\" Ð»Ð¸ÑˆÑŒ Ð´Ð»Ñ Ñ‚ÐµÐ±Ñ, Ð´Ñ€ÑƒÐ¶Ð¸Ñ‰Ðµ!"
      default_drinks:
        - name: Ð²Ð¾Ð´ÐºÐ°
          portion: 250
          intoxication: 30
          portions_per_day: 10
    en_US:
      name: American English
      greetings: "Hello everyone! My name is {0}, I'm serving drinks! :D\nHelp: {1}help. {2}"
      lang_selected: "Selected an \"en_US\" language!"
      on_error: "An unexpected error has occurred."
      missing_permissions:
        serve: "I haven't enough permissions for this command. Make sure I have permissions
              \"Move members\" and \"Add reactions\""
        drink: "I haven't enough permissions for this command. Make sure I have permission
                             \"Move members\""
      missing_role: "You're not barman."
      wrong_intoxication: "Parameter intoxication is not in the range from 0 to 100."
      wrong_portion_size: "Paramater portion_size is not positive"
      wrong_portions_per_day: "Parameter portions_per_day is not positive"
      wrong_drink_name: "Parameter drink_name is empty or its length more than {0} symbols"
      drink_not_found: "Drink \"{0}\" not found"
      drink_deleted: "Drink \"{0}\" deleted"
      drink_added: "Added \"{0}\" to the pub"
      duplicate_drink: "Duplicated drink found!"
      ok-emoji: "ðŸ‘"
      no-emoji: "ðŸ‘Ž"
      reset_complete: "Reset completed."
      reset_to_defaults_complete: "Default drink are restored."
      restocked_all: "All supplies are replenished! Here we go to drink again :D"
      serve_message:
        - "{author} offered you to drink {drink}, {portion_size}ml. Do you want it?"
      drink_info: "{0}, one portion is {1}ml, {2}/{3}"
      no_drinks: "There's no drinks!"
      joke_not_loaded: "The joke disappeared in an unknown direction :("
      too_many_drinks: "Cannot add a new drink: exceeded the limit of {0} positions"
      pre_overdrink:
        - "{0}'s eyes twitching..."
        - "{0} is almost done! Barman, finish him! >:D"
        - "{0} stoned out of his mind"
      overdrink_kick_message:
        - "{0} drank too much, got sent home before he broke something or someone"
        - "{0} fell to the floor. No, it wasn't a coronavirus, but it's the time for him to get some sleep and recover..."
        - "Heroically finishing his drink, {0} stood up with a flourish, walked a couple of meters and flew into the column. He will be cured, don't worry."
        - "{0} ran to the toilet, will be there soon! (probably)"
      overdrink_no_kick_message:
        - "{0} drank too much, but the bartender instantly sobered him up with some magic"
        - "{0} he was already blushing, but Aqua helped him... He's back ^_^"
      no_portions_left:
        - "{0} ran out too quickly..."
        - "{0} ran out. Do you want something else, mate?"
        - "God, no!\nHis Majesty, \"{0}\", completely gone :'("
      last_portion:
        - "It was the last drop of fine \"{0}\""
        - "This last portion of \"{0}\" is just for you, my friend!"
      default_drinks:
        - name: vodka
          portion: 250
          intoxication: 30
          portions_per_day: 10